Feature/s65 163
S65-2-project/frontend-service pull request #7
Opened 2020-05-12 10:59 UTC by Bstijn

2020-05-12 12:51 UTC, Chazler requested changes
Paar kleine schoonheids foutjes voor de rest puik werk!

2020-05-12 12:51 UTC, Chazler commented on src/profile/Profile.tsx
> +            var text = await response.text();
Veranderen naar const of let svp
```suggestion
            let text = await response.text();
```

2020-05-12 12:51 UTC, Chazler commented on src/profile/Profile.tsx
> +        var text =  await response.text();
Veranderen naar let svp
```suggestion
        let text =  await response.text();
```

2020-05-12 12:51 UTC, Chazler commented on src/profile/Profile.tsx
> +
```suggestion
```

2020-05-12 12:51 UTC, Chazler commented on src/profile/Profile.tsx
> +
```suggestion
```

2020-05-12 12:51 UTC, Chazler commented on src/profile/Profile.tsx
> +
```suggestion
```

2020-05-12 12:51 UTC, Chazler commented on src/profile/Profile.tsx
> +    let isDAppOwner : boolean = false;
```suggestion
    let changePassword = false; //Boolean which indicates if the user has decided to change to password.
    let oldPassword: string = ""; //String which has the oldPassword
    let newPassword: string = ""; //String which has the newPassword
    let repeatNewPassword: string = ""; //String which has the repeatNewPassword
      
    let isDelegate: boolean = false; //Boolean of isDelegate
    let isDAppOwner : boolean = false; //Boolean of isDAppOwner
```

2020-05-12 12:51 UTC, Chazler commented on src/profile/Profile.tsx
> +    // const [deleteProfileButtonBlock, setDeleteProfileButtonBlock] = React.useState(<div/>);
```suggestion
```

2020-05-12 12:51 UTC, Chazler commented on src/profile/Profile.tsx
> +
```suggestion
 
       /**
     * Runs when page loads in and the userId is filled in. will run again when editmode has been changed.
     */
```

2020-05-12 12:51 UTC, Chazler commented on src/profile/Profile.tsx
> +
```suggestion
```

2020-05-12 12:51 UTC, Chazler commented on src/profile/Profile.tsx
> +
```suggestion
```

2020-05-12 12:51 UTC, Chazler commented on src/components/TopNavigation.tsx
> +
```suggestion
```

2020-05-12 12:51 UTC, Chazler commented on src/components/TopNavigation.tsx
> +
```suggestion
```

2020-05-12 13:28 UTC, Bstijn commented
resolved white spaces en andere schoonheids foutjes

2020-05-15 07:46 UTC, Chazler approved these changes

2020-05-15 07:47 UTC, merged

2020-05-15 07:47 UTC, Chazler commented
Accepted